// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "github.com/trenchesdeveloper/go-ecom/types"
)

// ProductStore is an autogenerated mock type for the ProductStore type
type ProductStore struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: product
func (_m *ProductStore) CreateProduct(product types.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProduct provides a mock function with given fields: id
func (_m *ProductStore) GetProduct(id int) (*types.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *types.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*types.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *types.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByIDs provides a mock function with given fields: ids
func (_m *ProductStore) GetProductByIDs(ids []int) ([]types.Product, error) {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByIDs")
	}

	var r0 []types.Product
	var r1 error
	if rf, ok := ret.Get(0).(func([]int) ([]types.Product, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]int) []types.Product); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Product)
		}
	}

	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields:
func (_m *ProductStore) GetProducts() ([]types.Product, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []types.Product
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Product, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Product)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: product
func (_m *ProductStore) UpdateProduct(product types.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductStore creates a new instance of ProductStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductStore {
	mock := &ProductStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
